name: Deploy Docs

on:
  push:
    branches: ['main']
    path: ['docs/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Build
        working-directory: ./docs
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: quizms.olinfo.it
          publish_dir: ./docs/.vitepress/dist

